package org.sec.core;

public interface PassThroughData {
    Object[][] PASSTHROUGH_DATAFLOW = new Object[][]{
            {"java/lang/Object", "toString", "()Ljava/lang/String;", 0},
            {"java/io/ObjectInputStream", "readObject", "()Ljava/lang/Object;", 0},
            {"java/io/ObjectInputStream", "readFields", "()Ljava/io/ObjectInputStream$GetField;", 0},
            {"java/io/ObjectInputStream$GetField", "get", "(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;", 0},
            {"java/lang/Object", "getClass", "()Ljava/lang/Class;", 0},
            {"java/lang/Class", "forName", "(Ljava/lang/String;)Ljava/lang/Class;", 0},
            {"java/lang/Class", "getMethod", "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", 0, 1},
            {"java/lang/Class", "getMethods", "()[Ljava/lang/reflect/Method;", 0},
            {"java/lang/StringBuilder", "<init>", "(Ljava/lang/String;)V", 0, 1},
            {"java/lang/StringBuilder", "<init>", "(Ljava/lang/CharSequence;)V", 0, 1},
            {"java/lang/StringBuilder", "append", "(Ljava/lang/Object;)Ljava/lang/StringBuilder;", 0, 1},
            {"java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", 0, 1},
            {"java/lang/StringBuilder", "append", "(Ljava/lang/StringBuffer;)Ljava/lang/StringBuilder;", 0, 1},
            {"java/lang/StringBuilder", "append", "(Ljava/lang/CharSequence;)Ljava/lang/StringBuilder;", 0, 1},
            {"java/lang/StringBuilder", "append", "(Ljava/lang/CharSequence;II)Ljava/lang/StringBuilder;", 0, 1},
            {"java/lang/StringBuilder", "toString", "()Ljava/lang/String;", 0},
            {"java/io/ByteArrayInputStream", "<init>", "([B)V", 1},
            {"java/io/ByteArrayInputStream", "<init>", "([BII)V", 1},
            {"java/io/ObjectInputStream", "<init>", "(Ljava/io/InputStream;)V", 1},
            {"java/io/File", "<init>", "(Ljava/lang/String;I)V", 1},
            {"java/io/File", "<init>", "(Ljava/lang/String;Ljava/io/File;)V", 1},
            {"java/io/File", "<init>", "(Ljava/lang/String;)V", 1},
            {"java/io/File", "<init>", "(Ljava/lang/String;Ljava/lang/String;)V", 1},
            {"java/nio/paths/Paths", "get", "(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;", 0},
            {"java/net/URL", "<init>", "(Ljava/lang/String;)V", 1},
            {"javax/servlet/http/HttpServletRequest", "getParameter", "(Ljava/lang/String;)Ljava/lang/String;", 0},
            {"javax/servlet/http/HttpServletRequest", "getQueryString", "()Ljava/lang/String;", 0},
            {"javax/servlet/http/HttpServletRequest", "getParameterNames", "()Ljava/util/Enumeration;", 0},
            {"javax/servlet/http/HttpServletRequest", "getParameterValues", "(Ljava/lang/String;)[Ljava/lang/String;", 0},
            {"javax/servlet/http/HttpServletRequest", "getParameterMap", "()Ljava/util/Map;", 0},
            {"javax/servlet/http/HttpServletRequest", "getHeader", "(Ljava/lang/String;)Ljava/lang/String;", 0},
            {"javax/servlet/http/HttpServletRequest", "getHeaders", "(Ljava/lang/String;)Ljava/util/Enumeration;", 0},
            {"javax/servlet/http/HttpServletRequest", "getHeaderNames", "()Ljava/util/Enumeration;", 0},
    };
}
